name: Artifacts
permissions:
  contents: read
jobs:
  docs:
    name: Docs Preview
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: dev-infra-273822
      GCP_PR_BUCKET_ID: icu4x-pr-artifacts
    steps:
    - name: "\u2B50\u2B50\u2B50 Links to Uploaded Artifacts \u2B50\u2B50\u2B50"
      run: "echo \"\U0001F512 Credentials Info\"\necho \"The following artifacts are\
        \ built and uploaded in forks containing the ICU4X service account key. If\
        \ you are a frequent contributor, see 'artifacts-build.yml' for instructions\
        \ on setting up the key.\"\necho\necho \"\U0001F4D6 Rust docs\"\necho \"http://${{\
        \ env.GCP_PR_BUCKET_ID }}.storage.googleapis.com/gha/${{ github.event.pull_request.head.sha\
        \ }}/rustdoc/icu/index.html\"\necho\necho \"\U0001F4D6 C++ docs\"\necho \"\
        http://${{ env.GCP_PR_BUCKET_ID }}.storage.googleapis.com/gha/${{ github.event.pull_request.head.sha\
        \ }}/cppdoc/index.html\"\necho\necho \"\U0001F4D6 TypeScript docs\"\necho\
        \ \"http://${{ env.GCP_PR_BUCKET_ID }}.storage.googleapis.com/gha/${{ github.event.pull_request.head.sha\
        \ }}/tsdoc/index.html\"\necho\necho \"\U0001F4D6 Dart docs\"\necho \"http://${{\
        \ env.GCP_PR_BUCKET_ID }}.storage.googleapis.com/gha/${{ github.event.pull_request.head.sha\
        \ }}/dartdoc/index.html\"\necho\necho \"\U0001F4D6 Kotlin docs\"\necho \"\
        http://${{ env.GCP_PR_BUCKET_ID }}.storage.googleapis.com/gha/${{ github.event.pull_request.head.sha\
        \ }}/kdoc/icu4x/org.unicode.icu4x/index.html\"\necho\necho \"The links will\
        \ be available after the following job completes:\"\necho \"${{ github.event.pull_request.head.repo.html_url\
        \ }}/actions/workflows/artifacts-build.yml\"\n"
'on':
  workflow_dispatch: null
